site_name: Fanart.tv Wiki
site_description: Welcome to the Fanart.tv Docs
site_author: akovia
site_url: https://wiki.fanart.tv

repo_url: https://github.com/KodeStar/fanartwiki
repo_name: fanart.tv/site-documentation
edit_uri: ""

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  
markdown_extensions:
  - smarty
  - admonition
  - footnotes
  - abbr
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.details
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  
theme:
  name: material
  features:
    - navigation.instant
    - navigation.top

  language: en
  favicon: assets/images/favicon.ico
  logo: assets/images/fatv-logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  
nav:
    - Home: 'index.md'
    - FAQ: 'General/faq.md'
    - 'Site Information':
        - 'Help': 'General/fanart help.md'
        - 'Site Rules': 'General/site rules.md'
        - 'Staff': 'General/staff.md'
        - 'VIP Members': 'General/vip.md'
        - 'Moderation Time': 'General/moderation time.md'
        - 'Personal API Keys': 'General/personal api.md'
        - 'Moderating': 'General/moderating.md'
        - 'Remove Advertisements': 'General/remove adverts.md'
    - Guides:
        - 'Getting Started': 'General/getting started.md'
        - 'How Fanart.tv works': 'General/fanart database.md'
        - 'Contributor Guide': 'General/contributor guide.md'
        - 'Replace an Image': 'General/replace an image.md'
        - 'Retract a Submission': 'General/retract submission.md'
        - 'Why Was My Artwork Denied?': 'General/why denied.md'
    - Image Types:
        Movie Images:
            - 'Movie HD ClearLogo': 'ImageTypes/Movies/hdmovielogo.md' 
            - 'Movie HD Clearart': 'ImageTypes/Movies/hdmovieclearart.md' 
            - 'Movie Poster': 'ImageTypes/Movies/movieposter.md' 
            - 'Movie Background': 'ImageTypes/Movies/moviebackground.md' 
            - 'Movie Disc': 'ImageTypes/Movies/moviedisc.md' 
            - 'Movie Thumb': 'ImageTypes/Movies/moviethumb.md' 
            - 'Movie Banner': 'ImageTypes/Movies/moviebanner.md' 
        TV Images:
            - 'TV HD ClearLogo': 'ImageTypes/TV/hdtvlogo.md' 
            - 'TV HD ClearART': 'ImageTypes/TV/hdclearart.md' 
            - 'TV Poster': 'ImageTypes/TV/tvposter.md' 
            - 'TV Season Poster': 'ImageTypes/TV/seasonposter.md' 
            - 'TV Character Art': 'ImageTypes/TV/characterart.md' 
            - 'TV Background': 'ImageTypes/TV/showbackground.md' 
            - 'TV Banner': 'ImageTypes/TV/tvbanner.md' 
            - 'TV Season Banner': 'ImageTypes/TV/seasonbanner.md' 
            - 'TV Thumb': 'ImageTypes/TV/tvthumb.md' 
            - 'TV Season Thumb': 'ImageTypes/TV/seasonthumb.md' 
        Music Images:
            - 'Music HD ClearLogo': 'ImageTypes/Music/hdmusiclogo.md' 
            - 'Music Album Cover': 'ImageTypes/Music/albumcover.md' 
            - 'Music Artist Thumb': 'ImageTypes/Music/artistthumb.md' 
            - 'Music CDArt': 'ImageTypes/Music/cdart.md' 
            - 'Music Artist Background': 'ImageTypes/Music/artistbackground.md' 
            - 'Music Banner': 'ImageTypes/Music/musicbanner.md' 
            - 'Music Record Label': 'ImageTypes/Music/musiclabel.md' 

        

        
